site_name: Simple Docs Material+MkDocs Test
docs_dir: ./docs/
theme:
   name: material
nav:
   - Home: README.md
   - License: LICENSE.md
plugins:
   - macros
markdown_extensions:
   - abbr
   - admonition
   - attr_list
   - def_list
   - footnotes
   - meta
   - pymdownx.betterem:
      smart_enable: all
   - pymdownx.caret
   - pymdownx.critic
   - pymdownx.highlight:
      linenums: true
   - pymdownx.inlinehilite
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.snippets
   - pymdownx.superfences
   - pymdownx.tabbed
   - pymdownx.tasklist:
      custom_checkbox: true
   - pymdownx.tilde
